const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('tipprint', {
  appVersion: () => ipcRenderer.invoke('app-version'),
  listPorts: () => ipcRenderer.invoke('list-ports'),
  getLog: () => ipcRenderer.invoke('get-log'),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  btStatus: () => ipcRenderer.invoke('bt-status'),
  btDevices: () => ipcRenderer.invoke('bt-devices'),
  btKnownDevices: () => ipcRenderer.invoke('bt-known-devices'),
  btAdapterCheck: () => ipcRenderer.invoke('bt-adapter-check'),
  btPair: (id) => ipcRenderer.invoke('bt-pair', id),
  btRepair: (mac) => ipcRenderer.invoke('bt-repair', mac),
  openBtSettings: () => ipcRenderer.invoke('open-bt-settings'),
  connectSerial: (portPath, baud) => ipcRenderer.invoke('connect-serial', portPath, baud),
  connectNet: (host, port) => ipcRenderer.invoke('connect-net', host, port),
  disconnect: () => ipcRenderer.invoke('disconnect'),
  printRaw: (base64) => ipcRenderer.invoke('print-raw', base64),
  printTest: (printerLabel) => ipcRenderer.invoke('print-test', printerLabel),
  updateCheck: () => ipcRenderer.invoke('update-check'),
  updateDownload: () => ipcRenderer.invoke('update-download'),
  updateInstall: (installerPath) => ipcRenderer.invoke('update-install', installerPath),
  authSignup: (email, password) => ipcRenderer.invoke('auth-signup', email, password),
  authLogin: (email, password) => ipcRenderer.invoke('auth-login', email, password),
  authLogout: () => ipcRenderer.invoke('auth-logout'),
  authStatus: () => ipcRenderer.invoke('auth-status'),
  systemsList: () => ipcRenderer.invoke('systems-list'),
  systemsCreate: (name) => ipcRenderer.invoke('systems-create', name),
  systemsRevoke: (id) => ipcRenderer.invoke('systems-revoke', id)
});
